### ISSUE TITLE
Add support for macports

### ISSUE THREAD

**Issue by mprahl** [mprahl/ansible-role-lets-encrypt-route-53#29]
In PR #26, MacOS support was added with homebrew. It'd be nice to also add support for macports as an alternative that can be enabled with a role variable.

**Comment by ctipper** [comment]
Also a small modification but in `virtualenv.yml` I suggest the following to aid setting up the role:

```
- name: use the created virtualenv
  set_fact:
    ansible_python_interpreter: "{{ ler53_account_key_dir }}/ansible-lets-encrypt-virtualenv/bin/python"
  when: not ansible_check_mode
  tags:
  - install
  ```

**Comment by ctipper** [comment]
Final note I couldn't get virtualenv to execute without adding virtualenv_command, I'm using python 3
```
- name: install pyOpenSSL and boto in a virtualenv (Red Hat/ MacOS)
  pip:
    name: "{{ ler53_item.name }}"
    state: "{{ ler53_item.state | default(omit) }}"
    version: "{{ ler53_item.version | default(omit) }}"
    virtualenv: "{{ ler53_account_key_dir }}/ansible-lets-encrypt-virtualenv"
    # This is required for libselinux-python
    virtualenv_site_packages: yes
    virtualenv_command: /opt/local/bin/python -m venv
```
