### ISSUE TITLE
[macOS] venv not created

### ISSUE THREAD

**Issue by ctipper** [mprahl/ansible-role-lets-encrypt-route-53#56]
This seems to be a regression but task does not create venv in `ler53_account_key_dir`

TASK [mprahl.lets-encrypt-route-53 : install virtualenv (MacOS)] *****************************
changed: [localhost]

TASK [mprahl.lets-encrypt-route-53 : install pyOpenSSL and boto in a virtualenv (Red Hat/ MacOS)] ***
changed: [localhost] => (item={'name': 'setuptools', 'state': 'present'})
changed: [localhost] => (item={'name': 'pyOpenSSL'})
changed: [localhost] => (item={'name': 'boto3'})
changed: [localhost] => (item={'name': 'enum34'})
changed: [localhost] => (item={'name': 'ipaddress'})
changed: [localhost] => (item={'name': 'cffi'})

TASK [mprahl.lets-encrypt-route-53 : use the created virtualenv] *****************************
ok: [localhost]

TASK [mprahl.lets-encrypt-route-53 : generate the private key] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: /etc/ssl/lets_encrypt/ansible-lets-encrypt-virtualenv/bin/python: No such file or directory\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

python --version
Python 3.12.8

ansible --version
ansible [core 2.18.1]

**Comment by ctipper** [comment]
I created venv manually, and installed libraries manually. This task seems to be missing boto3.

**Comment by ctipper** [comment]
I don't know much about submitting a pull request but this is my suggestion to bring the task up to date, creating venv on macOS

```
- name: install virtualenv (MacOS)
  command: "{{ ansible_python_interpreter }} -m venv ansible-lets-encrypt-virtualenv"
  args:
    chdir: "{{ ler53_account_key_dir }}"
  when: ansible_os_family == 'Darwin'
  tags:
  - install

- name: Activate the virtual environment
  shell: source ansible-lets-encrypt-virtualenv/bin/activate
  args:
    chdir: "{{ ler53_account_key_dir }}"
  when: ansible_os_family == 'Darwin'
  tags:
  - install
  ```
